# Generated by Django 4.2 on 2023-04-12 14:57

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do cliente')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone para Contato')),
                ('endereco', models.TextField(verbose_name='Endereço do cliente')),
                ('referencia', models.TextField(verbose_name='Ponto de Referencia')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Debito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debito', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Debitos do Cliente')),
                ('data', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='cliente.cliente')),
            ],
        ),
    ]
