# Generated by Django 4.2 on 2023-04-12 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt_marmita', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Quantidade de Marmitas')),
                ('valor_marmita', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Marmita')),
                ('total_pedido', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total do pedido')),
                ('descricao', models.TextField()),
                ('is_pago', models.BooleanField(default=False, verbose_name='Pedido Pago?')),
                ('is_entregue', models.BooleanField(default=False, verbose_name='Pedido Entregue')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
    ]
