# Generated by Django 4.2 on 2023-04-12 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor entrada')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total de entradas')),
                ('razao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.pedido')),
            ],
        ),
    ]
