# Generated by Django 4.2 on 2023-04-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0005_totalentrada_remove_entrada_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total de entradas associadas ao pedido'),
        ),
    ]
