# Generated by Django 4.2 on 2023-04-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0006_entrada_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saida', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Saida')),
                ('data', models.DateField(auto_now_add=True)),
                ('descricao', models.TextField(verbose_name='Descrição da saida')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total de Saidas')),
            ],
        ),
    ]
