# Generated by Django 4.2 on 2023-04-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0007_saida'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total de entradas')),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
